### ISSUE TITLE
Every time loading all scripts and css not act like SPA ?

### ISSUE THREAD

**Issue by gsivaprabu** [csotomon/Angular2-AdminLTE#15]
How can i handle like SPA(Single Page Application). Whe ever the URL navigate to different at that time all scrips css are loading?

![image](https://user-images.githubusercontent.com/2444608/28712861-6656f2a8-73aa-11e7-9d7b-1e79b548bdad.png)

**Comment by csotomon** [comment]
All the files are only loaded the first time that the app loads.

You have to use routerLink to prevent the app reload.

For example:
`<a routerLink="dashboard2"><i class="fa fa-circle-o"></i> Dashboard v2</a>`
before click clear your network log and check it.
