### ISSUE TITLE
Control side bar 

### ISSUE THREAD

**Issue by TPJ11** [csotomon/Angular2-AdminLTE#18]
There are two small issues with the control side bar -

1) It does not take 100% height / its missing its background. This is because its missing the required div below the content aside 
at bottom of  `*-coontrol-sidebar.compoent.html ` add `<div class="control-sidebar-bg"></div>`

2) The admin template is not selecting the recent activity tab by default. This is because its missing the `active` class on both the li and the div. 

also this repository is not open for me to create a pull request with the fixes :/

**Comment by csotomon** [comment]
Hi @TPJ11 please check the contribution instructionsin README file.

Thank you for your issue report , i will check it this week or you can try to fork the project, fix the issue and create a push request.

**Comment by csotomon** [comment]
@TPJ11 the issue 
1) is fixed.
2) work in progress
