### ISSUE TITLE
Ng serve: no such file 

### ISSUE THREAD

**Issue by mmeendez8** [csotomon/Angular2-AdminLTE#21]
Hello, I just for your repo and after installing and configure it I obtained the following error:

>  10% building modules 3/3 modules 0 active/home/mmeendez/dashboard/node_modules/admin-lte/node_modules/webpack-concat-plugin/index.js:54
                        throw err;
Error: ENOENT: no such file or directory, open '/home/mmeendez/dashboard/node_modules/admin-lte/dist/js/app.js'

Your angular-cli.json is actually looking for that file that does not exist!
  

> 

    "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/jqueryui/jquery-ui.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js",
        "../node_modules/raphael/raphael.js",
        "../node_modules/morris.js/morris.js",
        "../node_modules/jquery-sparkline/jquery.sparkline.js",
        "../node_modules/jquery-knob/dist/jquery.knob.min.js",
        "../node_modules/moment/moment.js",
        "../node_modules/daterangepicker/daterangepicker.js",
        "../node_modules/bootstrap-datepicker/js/bootstrap-datepicker.js",
        "../node_modules/jquery-slimscroll/jquery.slimscroll.js",
        "../node_modules/bootstrap3-wysihtml5-bower/dist/bootstrap3-wysihtml5.all.js",
        "../node_modules/icheck/icheck.js",
        "../node_modules/admin-lte/dist/js/app.js",
        "assets/js/scripts.js"
      ],

Any idea?

**Comment by csotomon** [comment]
`../node_modules/admin-lte/dist/js/app.js` is the principal theme file. please run `npm install` again and check that the file exist, or try to delete node_modules folder and run `npm install` again

**Comment by csotomon** [comment]
@mmeendez8 please pull the last changes
