### ISSUE TITLE
Can't change AdminLTE options

### ISSUE THREAD

**Issue by szanellato93** [csotomon/Angular2-AdminLTE#24]
i tried to change the options of AdminLTE. I tried 2 way:

1) create a js file whe i declare the AdminLTEOptions  and load it with the angular-cli before the appjs. Nothing happened

2) change the options in $.AdminLTE.options and call the custom AdminLTE.init(). Nothing happened.

I tried with the  sidebarExpandOnHover and sidebar animation speed.. but nothing. I wronged anything?

**Comment by csotomon** [comment]
in this moment we are using adminLTE 2.3.11 and this version doesn't support AdminLTEOptions
