### ISSUE TITLE
integration with laravel and apache

### ISSUE THREAD

**Issue by efcjunior** [csotomon/Angular2-AdminLTE#27]
I've deployed this project together with framework laravel on apahce, but it's not working. Is not possible ?

**Comment by csotomon** [comment]
for what are you using Laravel? calling web services?

**Comment by efcjunior** [comment]
Hi, thank you for replying...
So, in my company we can't use nodejs and we would like to implement the
backend with laravel and front-end with angularjs...
We like so much of implementation, we have made in this way:

1- created new laravel project;
2- downloaded your implementation in public folder and executed ng build
for creating dist folder.
3- configured in laravel view.php file the path of index of angular.

In this moment, I've not created any controller. I would like only to make
your demo to work.

I'm for my English. I hope you  understand.

On Dec 15, 2017 11:29, "Camilo Soto Montoya" <notifications@github.com>
wrote:

for what are you using Laravel? calling web services?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/csotomon/Angular2-AdminLTE/issues/27#issuecomment-352005887>,
or mute the thread

**Comment by csotomon** [comment]
@efcjunior angular is just a frontend framework, and works independent from the backend implementation.

You can use Laravel to create an RESTful API and call it from the angular app using the HttpClient module.

Maybe this couple of links can help you.

[https://medium.com/codingthesmartway-com-blog/angular-4-3-httpclient-accessing-rest-web-services-with-angular-2305b8fd654b](https://medium.com/codingthesmartway-com-blog/angular-4-3-httpclient-accessing-rest-web-services-with-angular-2305b8fd654b)

[https://appdividend.com/2017/09/22/laravel-5-5-angular-4-tutorial-example-scratch/](https://appdividend.com/2017/09/22/laravel-5-5-angular-4-tutorial-example-scratch/)
