### ISSUE TITLE
Issue after Running ng serve 

### ISSUE THREAD

**Issue by SANTHK** [csotomon/Angular2-AdminLTE#3]
I am getting errors after running ng serve. 
Error:(10, 15) TS2503:Cannot find namespace 'morris'.
Error:(13, 9) TS2304:Cannot find name 'JQuery'.
Could you please help me out !

**Comment by csotomon** [comment]
npm uninstall -g angular-cli
npm cache clean
npm install -g @angular/cli

rm -rf node_modules dist # 

> use rmdir /S/Q node_modules dist in Windows Command Prompt; use rm -r -fo node_modules,dist in Windows PowerShell

npm install

Let me know if you have some problem
