### ISSUE TITLE
I cant browse data tables and many other componenets

### ISSUE THREAD

**Issue by Furqanaa** [csotomon/Angular2-AdminLTE#33]
Hi there,
I followed your instructions, I browsed http://localhost:4200/admin/dashboard1 and every thing works fine, but when browsing data tables I got a redirect to  http://localhost:4200, the same thing happened for many other pages such as forms, UI elements..etc

**Comment by csotomon** [comment]
Hi @Furqanaa you have to create yourself components, in this moment the links are just examples.

You can use [https://github.com/csotomon/Angular2-AdminLTE/tree/master/src/app/admin/admin-dashboard1](src/app/admin/admin-dashboard1) like and example.

Don't forget update your routes in [https://github.com/csotomon/Angular2-AdminLTE/blob/master/src/app/admin/admin-routing/admin-routing.module.ts](/src/app/app-routing/app-routing.module.ts).

Let me know if your need more help

**Comment by Furqanaa** [comment]
thank you for answering.

**Comment by csotomon** [comment]
You're welcome.

**Comment by Furqanaa** [comment]
can you please tell me if this is an angular4 or 2? because at the description you mentioned that this is an angular4 version but the name of the project is Angualr2 I'm confused!
