### ISSUE TITLE
issue in routing.

### ISSUE THREAD

**Issue by Lokendra2500** [csotomon/Angular2-AdminLTE#36]
I am facing the issue, when I try to route on other component.
I create a new component (citycomponent) and adding the routing path in app-routing.module.ts file. 

this is my route file

import { CityComponent } from './../city/city.component';
import { StarterComponent } from './../starter/starter.component';
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';

@NgModule({
  imports: [
    RouterModule.forRoot([
      { path: '', redirectTo: 'starter', pathMatch: 'full' },
      { path: 'starter', component: StarterComponent },
      { path: 'city', component: CityComponent }
    ])
  ],
  declarations: [],
  exports: [ RouterModule]
})
export class AppRoutingModule { }

and i also add router-outlet tag in my starter.component.html file.

this is the starter.component.html..

<div class="content-wrapper">
  
  <section class="content-header">
    <h1>
      Page Header
      <small>Optional description</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>

  
  <section class="content">

    
    <router-outlet></router-outlet>

  </section>
  
</div>

and I add my routerLink in starter-left-side.component.html.

but when i click on my router link it will not properly routed on my component.

**Comment by csotomon** [comment]
@Lokendra2500 can you share me your code?

**Comment by Lokendra2500** [comment]
this is my app.routing.ts code:

`import { CityComponent } from './../city/city.component';
import { StarterComponent } from './../starter/starter.component';
import { NgModule } from '';
import { RouterModule } from '';

@NgModule({
imports: [
RouterModule.forRoot([
{ path: '', redirectTo: 'starter', pathMatch: 'full' },
{ path: 'starter', component: StarterComponent },
{ path: 'city', component: CityComponent }
])
],
declarations: [],
exports: [ RouterModule]
})
export class AppRoutingModule { }`

this is my starter-content.component.html code:

`<div class="content-wrapper">
  
  <section class="content-header">
    <h1>
      Page Header
      <small>Optional description</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>

  
  <section class="content">

    
    <router-outlet></router-outlet>        // here i want to load my all pages...

  </section>
  
</div>
`

this is my starter.component.html file code:

`<div class="wrapper">
   
  <app-starter-header></app-starter-header>
  
  <app-starter-left-side></app-starter-left-side>
  
  <app-starter-content></app-starter-content>
  
  
  <app-starter-footer></app-starter-footer>
  
  <app-starter-control-sidebar></app-starter-control-sidebar>
  
  
  <div class="control-sidebar-bg"></div>
</div>
`
and my app.component.html file code is:

`<router-outlet></router-outlet>`

and I add two new components like city and state. Is this sufficient for you or not..??

**Comment by Lokendra2500** [comment]
@csotomon I simply download your angular2-adminlte theme, now I want to add some components.

I created two components like city and states now I want to route on these two component, but when I add these components in my app-routing file, it will not work.

Please help me.

**Comment by metalpapa** [comment]
same problem.

**Comment by metalpapa** [comment]
copy this in your city or state component 
```<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Page Header
      <small>Optional description</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
ssssssssssssssssssssssss
    <!-- Your Page Content Here -->

  </section>
  <!-- /.content -->
</div>

```

**Comment by metalpapa** [comment]
i have the same problem. and this is what i discovered.
in the starter-content.componet.html i put 
![imagen](https://user-images.githubusercontent.com/20878310/35297785-a190ebac-005a-11e8-8da3-e0b8f5dfdee3.png)

i create a component "servicechat"
![imagen](https://user-images.githubusercontent.com/20878310/35297828-caa0d548-005a-11e8-8c0f-3d4534286c81.png)
and work. servicechat is call from starter

this is why 

![imagen](https://user-images.githubusercontent.com/20878310/35297928-12ab1fa6-005b-11e8-993d-67025e160f74.png)

**Comment by csotomon** [comment]
the starter component is just an example of how you have to create new modules and components for your app. Specifically, what do you need?
