### ISSUE TITLE
Page size is too big

### ISSUE THREAD

**Issue by basitsattar** [csotomon/Angular2-AdminLTE#39]
I am loading starter template and it is using more than 13 mb of bandwidth. How much is the size after AOT compilation? Can I remove plugins like charts.js if I don't plan to add any charts without modifying the adminlte npm package?

**Comment by csotomon** [comment]
hi, the theme have a lot of plugins that you can or not use them in your app. You can remove all the unnecessary plugins.

Remember remove all dependencies from /.angular-cli.json file (check the css and js files).

I never tried compile the app with AOT support, and i don't know the size with this option. Also the code is not yet optimized to support AOT.

did you tried to compile the app with --prod option? that option significantly reduces the size
