### ISSUE TITLE
content-wrapper min-height and control-sidebar with child module

### ISSUE THREAD

**Issue by deio89** [csotomon/Angular2-AdminLTE#4]
Hi, when I create a new child module and navigate to that, the content-wrapper min-height doesn't resize. The control-sidebar stops working too!

![image](https://cloud.githubusercontent.com/assets/17225572/24751230/2477922a-1a9f-11e7-8aaf-0f3ac6372fb8.png)

I've tried to call  jQuery.AdminLTE.layout.activate(); but with angular 4 doesn't works anymore and result with error _EXCEPTION: Error in :0:0 caused by: Cannot read property 'activate' of undefined_

**Comment by csotomon** [comment]
I'll check it next week

**Comment by nileshyadav326** [comment]
have to checked.

**Comment by csotomon** [comment]
This is fixed in the new version

**Comment by redgyuf** [comment]
Hi, I have a very similar problem.

When i navigate to a component with routerLink, the min-height of content-wrapper is too small. If I resize the browser then it starts to work like it should.
