### ISSUE TITLE
Doubts about a use

### ISSUE THREAD

**Issue by atiladelcanton** [csotomon/Angular2-AdminLTE#40]
Good Morning.

I'm trying to use it, but I have some doubts

1 - Which folder do I use to develop ? 

2 - How do I arrange the route to drop the default inside the admin folder?

Sorry for the questions I'm new at angular

Att.

**Comment by csotomon** [comment]
Hi,

1 - you have to use the angular-cli to compile the app, and just run the angular-cli commands in the root folder.

2- First, you must understand how the angular 4 routing works, you can learn the angular tutorial here [(https://angular.io/tutorial/toh-pt5](https://angular.io/tutorial/toh-pt5)] , you have to change /src/app/app-routing/app-routing.module.ts with a lot alternatives, por example.

`{ path: '', component: AdminComponent },`

and after that you have to change this file /src/app/admin/admin-routing/admin-routing.module.ts to change the routes depending what you want with your app.

but the secret is understand how the Angular routing works.
