### ISSUE TITLE
Strange Behavior with control sidebar

### ISSUE THREAD

**Issue by DarioN1** [csotomon/Angular2-AdminLTE#41]
Hi,

I'have implemented Angular2-AdminLTE and I'm having some problem with the control sidebar.

The behavior is really strange:

If I click on the link:

`<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>`

The content is not appearing but if I try to load the page, change the browser tab while is loading and I come back to the page... If I click on the href the control sidebar appears properly...

I don't know whats is happening.

I have to say that I have customized the starter component in order to implement router-outlet.

The starter component now looks like this:

```
<div class="wrapper">
   <!-- Main Header -->
  <app-starter-header></app-starter-header>
  <!-- Left side column. contains the logo and sidebar -->
  <app-starter-left-side></app-starter-left-side>
  <!-- Content Wrapper. Contains page content -->
  <!--<app-starter-content></app-starter-content>-->
  
  <router-outlet></router-outlet>
   
  <!-- /.content-wrapper -->
  <!-- Main Footer -->
  <app-starter-footer></app-starter-footer>
  <!-- Control Sidebar -->
  <app-starter-control-sidebar></app-starter-control-sidebar>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div> 

```

How can I fix it ?

Thanks to support

**Comment by REJack** [comment]
You need to activate controlSidebar() too it's not automaticly loaded, look at dist/js/demo.js.

**Comment by DarioN1** [comment]
Thanks REJack, I saw the code... But I really don't know how to fix it...
Seems that control-sidebar is not initialize at first rendering...

**Comment by REJack** [comment]
If you doesn't want to use the skin change etc from the demo, you need only to add this `$('[data-toggle="control-sidebar"]').controlSidebar();` else try to load the demo.js it work with custom contents but loads every time the skin change stuff etc.

**Comment by DarioN1** [comment]
Thanks REJack, I tryed to add it into the component.ts file but I get this error:

error TS2339: Property 'controlSidebar' does not exist on type 'JQuery<HTMLElement>'

**Comment by REJack** [comment]
Oh shit this was for AdminLTE v2.4.X, i forgot that this project uses still v2.3.11 and the strange part is that control-sidebar get loaded automaticly in v2.3.11, it should work out of the box :/.

Look over the [old blank.html](https://raw.githubusercontent.com/almasaeed2010/AdminLTE/v2.3.11/pages/examples/blank.html) maybe your html markup has failures.

**Comment by DarioN1** [comment]
Thanks Jack, I give a look. I don't think the problem is related to the markup but on how I have structured the components in my Angular application...
If I run the template as is, it works perfectly...
What I did is custimize it in order to have the router-outlet inside the Starter component.

the starter.component.html looks like this now:

```
<div class="wrapper">

  <app-starter-header></app-starter-header>
  
  <app-starter-left-side></app-starter-left-side>
  
  <!--<app-starter-content></app-starter-content>-->
  
  <router-outlet></router-outlet>
   
  <app-starter-footer></app-starter-footer>

  <app-starter-control-sidebar></app-starter-control-sidebar>

    <div class="control-sidebar-bg"></div>
</div> 
```
May be that the strange behavior come from how I have structured the solution...

**Comment by REJack** [comment]
Did you changed stuff in starter-control-sidebar.component.html too? 

I'm not a Angular pro but if you want to use AdminLTE over your whole App you should implement this code into app.component.html, maybe this helps ;)

**Comment by DarioN1** [comment]
I'm not a pro too with angular...

Now I'm starting to work on the template from zero...

What I want to avoid in my project is to keep header, footer and leftmenu common for all the subbomponents injected into the application...

For sure I'm doing something wrong but I cannot explain how possible the application works properly if while it loads I switch browser tab and I come back again...

**Comment by DarioN1** [comment]
Yes, I'm having a look too... Admin page is what I have to customize... I just have to add another router outlet in order to manage different control sidebars...

**Comment by DarioN1** [comment]
After lot of search I discover that there are lot of problems in implementing AdminLte2 with Angular:

https://github.com/almasaeed2010/AdminLTE/issues?utf8=%E2%9C%93&q=angular

In my case all depends on how I inject component and multiple router-outlet ...

I'm still searching for a solution

**Comment by gauravtyagi77** [comment]
Did anyone find solution for it. I found a partial solution, if i use "window.location.assign('');" in place of "this.router.navigate(['/instances/active']);"  than it works but "window.location.assign('');" work fine on angular server but when I run this code on we server it miss context path in start of URL and giving an issue. Some one has found any permanent solution, please share.

**Comment by csotomon** [comment]
I'll keep it in mind for 2.4 version.

**Comment by csotomon** [comment]
closed for inactivity

**Comment by rodrigors3012** [comment]
Tenho este codigo no starter.header.component.html.

` <li>
              <a data-toggle="control-sidebar" ><i class="fa fa-gears"></i></a>
            </li>`

Quando abro funciona, mas se eu navego para outra página através do router.navigation deixa de funcionar.
