### ISSUE TITLE
template is not rendered in full screen

### ISSUE THREAD

**Issue by joaoroyosilva** [csotomon/Angular2-AdminLTE#42]
Good morning, my template is not being rendered on the full screen of the browser. There's a blank part. This happens when there is little content. Has anyone ever experienced this?

**Comment by LaeraFelipe** [comment]
I solve this way: `ngOnInit() {
    $('body').layout('fix');
  }`

**Comment by joaoroyosilva** [comment]
Thanks!

**Comment by LaeraFelipe** [comment]
:D
