### ISSUE TITLE
widgets,forms, UI elements missing.

### ISSUE THREAD

**Issue by zmrfzn** [csotomon/Angular2-AdminLTE#45]
Widgets, UI elements, forms, calendars and others components missing. 
Also please include documentation

**Comment by csotomon** [comment]
What brach are U using?

**Comment by zmrfzn** [comment]
master.

**Comment by csotomon** [comment]
In the actual master you can find the starter page to use in your project, and we have only the dashboard1 demo.

For 2.4.3 version i will create al the pages of the original theme, but this version is under development right now.

**Comment by csotomon** [comment]
This is under development in 3.0.0 version
